### ISSUE TITLE
Github Action web deploy failing (403).

### ISSUE THREAD

**Issue by jayypluss** [crystal-bit/godot-game-template#71]
After I've created a repo from this template, the Build Action for **Web** is failing with error:

```
remote: Permission to jayypluss/BreezyWave.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/jayypluss/BreezyWave.git/': The requested URL returned error: 403
```

Is there any action needed for this build action to work?

Link for the failing build line:
https://github.com/jayypluss/BreezyWave/runs/6251779089?check_suite_focus=true#step:9:99

Thanks!

**Comment by davcri** [comment]
Hi @jayypluss thanks for reporting the issue. 

I think that something changed in the default GitHub setup and broke the web build. In order to fix the issue try these steps on your GitHub repo:

- open the settings tab
- go to `Actions -> Genera -> Workflow permissions`
- select `Read and Write permissions`
- trigger a new workflow (eg: push a new commit)

I'm not sure this is the best way to handle the problem, but it should work at least.

**Comment by jayypluss** [comment]
Thanks, I did that and now the build is not failing anymore, **but** actually the deployed link is still showing the `godot-game-template`, and not my actual game in it's current state.

**Comment by davcri** [comment]
You can use https://jayypluss.com/BreezyWave/ to access your game. It seems that the deploy worked fine :) 

Probably I shoud add instructions because not everyone knows how GitHub handles pages URL

**Comment by jayypluss** [comment]
Yeah I did check it out, but actually at the time I've said that the URL had not updated yet. I didn't know it would take some time. Thanks for the help and patience!
