### ISSUE TITLE
Debug shortcuts are still functional on release builds

### ISSUE THREAD

**Issue by Evanaellio** [crystal-bit/godot-game-template#86]
The debug shortcuts (Q to quit, R to restart and P to pause) are still enabled even on a release build, so players might trigger them by accident.

**Comment by Evanaellio** [comment]
This is how we fixed that in our game : https://github.com/Evanaellio/ludumdare54/commit/88d74f597b7cb8cd063b71ad2cd440d2d15f2474

**Comment by davcri** [comment]
Hi @Evanaellio, thank you very much for reporting the issue.
Sorry for the bug, I backported this functionality from one of my jam games and I made a mistake.

The best approach is to remove the DebugShortcuts scene entirely if the game is running in releas builds so that performance are not affected.  

https://github.com/crystal-bit/godot-game-template/blob/main/addons/ggt-debug-shortcuts/autoload/debug_shortcuts.gd
